# Advanced 403 Bypass Tool Configuration
# Customize settings for optimal performance and safety

# Performance Settings
threads: 25                    # Number of concurrent threads
timeout: 15                    # Request timeout in seconds
delay: 0.05                    # Base delay between requests (adaptive)
max_retries: 3                 # Maximum retry attempts
adaptive_rate_limiting: true   # Enable intelligent rate limiting

# AI and Analysis Settings
enable_ai_analysis: true       # Enable AI-powered response analysis
similarity_threshold: 0.85     # Similarity threshold for response clustering
confidence_threshold: 0.5      # Minimum confidence for bypass detection
save_responses: false          # Save full response bodies (disk intensive)

# User Agent Rotation
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0"
  - "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/120.0.0.0 Safari/537.36"

# Bypass Categories to Enable
enabled_categories:
  - "Classic"          # Traditional bypass techniques
  - "Cloud"           # AWS, Azure, GCP specific bypasses
  - "CDN"             # Cloudflare, Akamai, Fastly bypasses
  - "API"             # REST, GraphQL, API versioning
  - "Container"       # Docker, Kubernetes bypasses
  - "Framework"       # Next.js, React, Vue, Serverless
  - "Encoding"        # Advanced encoding techniques
  - "WAF"             # WAF-specific bypasses
  - "Modern"          # Latest 2024+ techniques

# Custom Headers (applied to all requests)
global_headers:
  Accept: "*/*"
  Accept-Language: "en-US,en;q=0.9"
  Accept-Encoding: "gzip, deflate, br"
  Cache-Control: "no-cache"
  Pragma: "no-cache"

# Proxy Settings (optional)
proxy:
  enabled: false
  http: ""              # http://proxy:port
  https: ""             # https://proxy:port
  auth:                 # Optional proxy authentication
    username: ""
    password: ""

# Output Settings
output:
  format: "json"        # json, html, csv, xml
  include_headers: true # Include response headers in output
  include_timing: true  # Include detailed timing information
  compress: false       # Compress output files

# Database Settings
database:
  enabled: true         # Enable result storage
  path: "bypass_results.db"
  retention_days: 30    # Auto-cleanup old results

# Logging Settings
logging:
  level: "INFO"         # DEBUG, INFO, WARNING, ERROR
  file: "bypass.log"
  max_size_mb: 100
  backup_count: 5

# Safety and Ethics
safety:
  max_requests_per_second: 50   # Rate limiting
  respect_robots_txt: false     # Check robots.txt (not recommended for security testing)
  user_consent_required: true   # Require explicit consent
  
# Advanced Features
advanced:
  wayback_machine: true         # Check Wayback Machine for historical data
  subdomain_enumeration: false  # Enumerate subdomains (requires additional tools)
  port_scanning: false          # Basic port scanning (use with caution)
  ssl_analysis: true            # Analyze SSL/TLS configuration
  
# Custom Payloads
custom_payloads:
  paths:
    - "/secret"
    - "/hidden"
    - "/internal"
    - "/private"
    - "/confidential"
  
  headers:
    - {"X-Custom-Auth": "bypass"}
    - {"X-Admin-Panel": "true"}
    - {"X-Debug-Mode": "1"}

# Cloud Provider Specific Settings
cloud_providers:
  aws:
    regions: ["us-east-1", "us-west-2", "eu-west-1"]
    services: ["s3", "lambda", "api-gateway", "cloudfront"]
  
  azure:
    regions: ["eastus", "westus2", "westeurope"]
    services: ["blob", "functions", "app-service"]
  
  gcp:
    regions: ["us-central1", "us-east1", "europe-west1"]
    services: ["storage", "functions", "app-engine"]

# Framework Detection
frameworks:
  detect_automatically: true
  supported:
    - "nextjs"
    - "react"
    - "vue"
    - "angular"
    - "django"
    - "flask"
    - "express"
    - "spring"
    - "laravel"
    - "wordpress"

# Reporting
reporting:
  include_screenshots: false    # Requires additional dependencies
  generate_pdf: false          # Generate PDF reports
  email_results: false         # Email results (requires SMTP config)
  webhook_url: ""              # Send results to webhook

# SMTP Configuration (for email reports)
smtp:
  server: ""
  port: 587
  username: ""
  password: ""
  use_tls: true
  from_email: ""
  to_emails: []