name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application
      run: |
        python -c "import app; print('✅ App imports successfully')"
    
    - name: Test Docker build
      run: |
        docker build -t bypass-tool-test .
        docker run --rm -d -p 8000:8000 --name test-container bypass-tool-test
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy notification
      run: |
        echo "🚀 Deploying 403 Bypass Tool to production..."
        echo "📍 Will be available at: bypass403.arafatops.com"